### ISSUE TITLE
Add Django 4.2 in CI

### ISSUE THREAD

**Issue by iamsobanjaved** [openedx-unsupported/edx-analytics-dashboard#1488]
In order to have support for Django 4.2, we first need to run tests on Django 4.2 in the insights service. For updating CI, we should run tox and GitHub actions modernizers.

Tox Modernizer: [tox_moderniser_django42.py](https://github.com/openedx/repo-tools/blob/master/edx_repo_tools/codemods/django42/tox_moderniser_django42.py)

Github Action Modernizer: [github_actions_modernizer_django42.py](https://github.com/openedx/repo-tools/blob/master/edx_repo_tools/codemods/django42/github_actions_modernizer_django42.py)

```[tasklist]
### A/C
- [x] Run tests with Django 4.2
- [x] Fix all test failures with Django 4.2 (if any)
- [ ] After merging, ask the owning squad to add Django 4.2 tests in branch protection rules
```

**Comment by UsamaSadiq** [comment]
Created PR https://github.com/openedx/edx-analytics-dashboard/pull/1498 to fix the deprecations needed for Django 4.2 tests.

**Comment by UsamaSadiq** [comment]
CI checks are currently not running in the repo. To verify the Django 4.2 upgrade, we need to enable the CI checks first.

**Comment by UsamaSadiq** [comment]
For Django 4.2 upgrade, we need new version of pinax-announcements==4.0.1 with the fix for django.conf.urls. The PR for this fix has already been created against the upstream package and issue has been created with no response from the package maintainers. https://github.com/pinax/pinax-announcements/pull/74.
