### ISSUE TITLE
There are some problem when i executed the command make develop, can anyone to help me!? Please

### ISSUE THREAD

**Issue by jeremy55662004** [openedx-unsupported/edx-analytics-dashboard#252]
howard@howard-VirtualBox:~/edx-analytics/edx-analytics-dashboard$ make develop
npm install
./node_modules/.bin/bower install
bower extra-resolution      Unnecessary resolution: cldrjs#0.3.10
pip install -q -r requirements/base.txt --exists-action w
    Command "/usr/bin/python -c "import setuptools, tokenize; **file**='/home/howard/edx-analytics/edx-analytics-dashboard/src/edx-analytics-data-api-client/setup.py'; exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" develop --no-deps" failed with error code 1 in /home/howard/edx-analytics/edx-analytics-dashboard/src/edx-analytics-data-api-client
make: **\* [requirements] Error 1

There are some problem when i executed the command make develop, can anyone to help me!? Please, Thank you so much!

**Comment by clintonb** [comment]
The problem seems to lie with edx/edx-analytics-data-api-client. You can learn more by running pip directly with `--verbose` to learn more information.

Note that while this repository is public, we aren't fully ready to support users setting up their own installations. Additionally, in order to use the dashboard, you need to first have the pipeline and API setup to provide actual data to the dashboard. We intend to provide better support in the coming months. For now, if you don't have a pipeline setup, I would advise against proceeding with attempts to setup the dashboard.
