### ISSUE TITLE
Having an Issue with Bower Dependendencies while installing insights

### ISSUE THREAD

**Issue by theroadnotaken** [openedx-unsupported/edx-analytics-dashboard#581]
Hi,

We are trying to install insights and are having issues with Bower dependecies. We have tried it with different combinations but it always fails at Bower dependencies. We are installing this on a fresh AWS EC2 instance with Ubuntu 12.04.

Below is the Error Log we get:
[Error-Log.txt](https://github.com/edx/edx-analytics-dashboard/files/594901/Error-Log.txt)

We suspect this is an issue with the verisions of dependecies.
Please help us on this issue.

Regards
Srikanth Kanuri
srkanuri@iu.edu

**Comment by dsjen** [comment]
Hi Srikanth, I responded to your question on slack.  In short, it looks like the bower dependencies failed, but the sass compilation step was killed.  We're directing users to our edx analytics slack channel and to the [mailing list](https://groups.google.com/forum/#!forum/openedx-analytics) rather than using the github issues.
