### ISSUE TITLE
Prerequisites for installing AWS Bitnami Open Edx Analytics Dashboard

### ISSUE THREAD

**Issue by hemant816** [openedx-unsupported/edx-analytics-dashboard#623]
Hi,

Can you please guide me regarding the Prerequisites for installing AWS Bitnami Open Edx Analytics Dashboard. Also if Pipeline, Insights are to be installed at the same time for the Analytics Dashboard to work on AWS Bitnami Open Edx?

**Comment by dsjen** [comment]
Hi, I haven't used that particular version, but you'll find instructions for installing at:
* http://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/installation/analytics/install_analytics.html

Insights is the analytics dashboard and does require the data generated by the data pipeline in order to show anything meaningful.  Setting up the pipeline is definitely the first part o getting your system set up.  Please direct questions to https://groups.google.com/forum/#!forum/openedx-ops.

Thanks,
Dennis
